### ISSUE TITLE
What version of this code (and of selenium-webdriver) will actually run with redline13?

### ISSUE THREAD

**Issue by plumdog** [redline13/webdriverjs#2]
First of all, is this indeed the right repository for the "WebDriver NodeJS" plugin available on Redline13? The link there takes me to https://github.com/redline13/plugin-webdriver-node which 404s. If not, then apologies.

My actual questions:

- what version of this will run when I upload and run a test file? There are no releases/tags here. Does it checkout master from here each time my tests run? Or might I be getting an old version?
- what version of selenium-webdriver will be used? `package.json` just says `"selenium-webdriver": "^3.5"` which does leave some wiggle room. Are there some docs that might help me here?

I've arrived here because I'm getting errors when running through redline13 that I don't get locally with just an `npm install redline13-webdriver`. What code is even running when I upload and run a test?

**Comment by richardfriedman** [comment]
yes - the right plugin.  

> What version 

It comes from this npmjs module - https://www.npmjs.com/package/redline13-webdriver
We control the version, currently we install 0.4.0  (npm install redline13-webdriver@0.4.0) which is the latest. 

> There are no releases/tags here

Good catch, we just npmjs.org and package.json.  Will add that to the build step, thanks.

> what version of selenium-webdriver will be used?

Currently, it picks 3.6.0.  On the load agents, we do try to control for this. 

> Are there some docs that might help me here?

Here is current what we run on load agents.
https://www.redline13.com/blog/2018/03/webdriver-chrome-firefox-headless-load-testing/

>  I'm getting errors when running through redline13 

Please feel free to email info@redline13.com so we can get some more details about your tests and resolve any issues you have.

**Comment by plumdog** [comment]
In trying to write a minimal example to reproduce the errors I was getting, I think I've found my problem.

My setup had looked like:
```javascript
const redline = require('redline13-webdriver');
redline.webdriver.promise.USE_PROMISE_MANAGER = false;
const driver = redline.loadBrowser(BROWSER);
// ... code here
```
(See https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs for some stuff about the promise manager.)

And with this, my tests gave me errors like:
```
Starting test.
 Running tests #1 - 1
 Config:
 { load_resources: '1',
   serverCount: '1',
   classFilename: 'RedLineWebDriver.js',
   customFile: 'run.js',
   classPackage: '',
   classname: 'RedLineWebDriver.js',
   nvm_nodeversion: '8',
   webdriver_node_browser: 'chrome',
   webdriver_node_capture: 'on',
   webdriver_node_width: '1220',
   webdriver_node_height: '800',
   webdriver_node_depth: '24',
   plugins: 'nvm,webdriver_node',
   nvm: '1',
   webdriver_node: '1' }
 Start time: 1523748892
 Setting up Redline API.
 Loading class.
 Starting test in 46865ms.
 Load webdriver test: run.js
 Catch - Promise LoadTest Failing TypeError: Unable to create a managed promise instance: the promise manager has been disabled by the SELENIUM_PROMISE_MANAGER environment variable: false
     at new ManagedPromise (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:1030:13)
     at new Deferred (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:1454:20)
     at new Task (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:2778:5)
     at ControlFlow.execute (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:2477:16)
     at thenableWebDriverProxy.schedule (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
     at Navigation.to (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
     at thenableWebDriverProxy.get (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/webdriver.js:988:28)
     at main (/home/user58269/run.js:55:12)
     at Object.<anonymous> (/home/user58269/run.js:74:1)
     at Module._compile (module.js:652:30)
 Exception creating SNAP for error-1523748898331.png TypeError: Unable to create a managed promise instance: the promise manager has been disabled by the SELENIUM_PROMISE_MANAGER environment variable: false
     at new ManagedPromise (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:1030:13)
     at new Deferred (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:1454:20)
     at new Task (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:2778:5)
     at ControlFlow.execute (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:2477:16)
     at thenableWebDriverProxy.schedule (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
     at thenableWebDriverProxy.takeScreenshot (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/webdriver.js:1085:17)
     at /nodeshare/plugin_installs/node_modules/redline13-webdriver/index.js:178:28
     at new Promise (<anonymous>)
     at Function.RedLineWebDriver.snap (/nodeshare/plugin_installs/node_modules/redline13-webdriver/index.js:176:10)
     at /home/user58269/RedLineWebDriver.js:61:16
 Add close webdriver (quit) to end of sequence!
 Catch - Promises ALL failing undefined
```
By removing the `USE_PROMISE_MANAGER = false` line, my simple test did what I expected. But locally, it works with or without it. I can't really work out why - an old version of selenium-webdriver seemed like the most likely cause. If you can replicate this, it might be worth documenting it as a gotcha to be avoided, or perhaps trying to work out what it actually going on.

At any rate, I think I've found a solution to my problem.

**Comment by plumdog** [comment]
OK, it turns out that was one of my problems, but I had another. The browser was quitting before any of my tests actually ran, but only on redline13. They ran just fine locally.

It seems that using a function that looks like
```javascript
delay = millis => new Promise(res => setTimeout(res, millis));
```
to put some delays between bits of the test was the root cause of these problems. By patching `driver.quit` to print a trace, I could see what it was that was quitting my browser:
```
Start time: 1523878879
Setting up Redline API.
Loading class.
Starting test in 46326ms.
Load webdriver test: run_suite_simple.js
Then - waitAndCallback
Add close webdriver (quit) to end of sequence!
Calling driver quit
Trace: Calling driver quit
    at thenableWebDriverProxy.dr.quit.failed [as quit] (/home/user58328/run_suite_simple.js:237:13)
    at RedLineWebDriver.closeWebDriver (/home/user58328/RedLineWebDriver.js:102:37)
    at RedLineWebDriver.waitAndCallback (/home/user58328/RedLineWebDriver.js:80:31)
    at /home/user58328/RedLineWebDriver.js:55:10
    at ManagedPromise.invokeCallback_ (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /nodeshare/plugin_installs/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
GOOD: WEBDRIVER QUIT!
Callback on tests running!
...
[[logs from my tests starting and trying to open a page]]
Error running test: Redline13 selenium test
{ NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
...
```
So this curious `/home/user58328/RedLineWebDriver.js` file is doing something to make sure the browser gets closed. (I have stopped short of writing a test to include its contents in a test output because that feels cheeky.) But in this case it is running when it shouldn't. Without seeing how my custom code is harnessed, it's hard say for sure what is going on. This may also explain why setting `USE_PROMISE_MANAGER = false` was breaking things.

At any rate, this change of behaviour between local testing and running in on redline13 is pretty nasty, and was a pain to get to the bottom of. I have got around this by using `driver.sleep` instead.

To try to help future newbies like myself, I may investigate a way of emulating this behaviour locally, and write some hello-world example tests.

**Comment by avg00r** [comment]
I've got the same problem when I trying to use await for webdriver calls.
So, using driver.sleep instead of await is only one solution for now?
